package com.poc.excelplugin.controller;

import com.poc.excelplugin.dto.ExcelRequest;
import com.poc.excelplugin.service.ExcelService;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

@Slf4j
@RestController
@RequestMapping("/api/excel")
public class ExcelController {

    @Autowired
    private ExcelService excelService;

    // Updated to the path from your snippet
    private static final String OUTPUT_FOLDER = "C:\\Logs\\excel-files\\";

    @PostMapping("/generate")
    public ResponseEntity<String> generateAndSaveExcel(@RequestBody ExcelRequest request) {
        String context = (request.getContextName() != null) ? request.getContextName() : "output";
        log.info(">>> API HIT: Received request for Context: '{}'", context);

        try {
            // Service now adds UUID and HMAC Signature
            byte[] excelContent = excelService.generateGenericExcel(request);

            String filename = context + ".xlsx";
            log.info("Saving file as: '{}'", filename);

            Path path = Paths.get(OUTPUT_FOLDER + filename);
            if (!Files.exists(path.getParent())) {
                Files.createDirectories(path.getParent());
            }

            Files.write(path, excelContent);
            return ResponseEntity.ok("SUCCESS: File created at " + path.toAbsolutePath());

        } catch (IOException e) {
            log.error(">>> ERROR: IO Exception.", e);
            return ResponseEntity.internalServerError().body("ERROR: " + e.getMessage());
        } catch (Exception e) {
            log.error(">>> ERROR: Unexpected error.", e);
            return ResponseEntity.internalServerError().body("Unexpected Error: " + e.getMessage());
        }
    }

    @PostMapping("/verify")
    public ResponseEntity<String> verifyExcelFile(@RequestParam("file") MultipartFile file) {
        if (file.isEmpty()) {
            return ResponseEntity.badRequest().body("Please upload a file.");
        }

        try (XSSFWorkbook workbook = new XSSFWorkbook(file.getInputStream())) {

            // 1. Verify integrity and get the UUID
            try {
                // The service checks the HMAC signature using the SECRET_KEY.
                // If this succeeds, it GUARANTEES the file was created by this platform.
                String fileId = excelService.verifyFileIntegrity(workbook);

                return ResponseEntity.ok("✅ VALID PLATFORM FILE. File Identity: " + fileId);

            } catch (SecurityException e) {
                // Check the error message to distinguish the failure reason
                String errorMsg = e.getMessage();

                // If the error says "No signature" or "No File ID", it means the file
                // didn't originate from our platform at all.
                if (errorMsg != null && (errorMsg.contains("No signature") || errorMsg.contains("No File ID"))) {
                    return ResponseEntity.status(400).body("❌ INVALID ORIGIN: This file was NOT generated by our platform (Missing Signature).");
                }
                // Otherwise, it has the ID but the signature doesn't match the content
                else {
                    return ResponseEntity.status(401).body("❌ TAMPERED: This is a platform file, but the data has been modified externally.");
                }
            }

        } catch (IOException e) {
            return ResponseEntity.internalServerError().body("Error reading file: " + e.getMessage());
        }
    }
}