package com.poc.excelplugin.controller;

import com.poc.excelplugin.dto.ExcelRequest;
import com.poc.excelplugin.service.ExcelService;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.openxmlformats.schemas.officeDocument.x2006.customProperties.CTProperty; // Import needed for POI 5.x
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

@Slf4j
@RestController
@RequestMapping("/api/excel")
public class ExcelController {

    @Autowired
    private ExcelService excelService;

    // Hardcoded path
    private static final String OUTPUT_FOLDER = "C:\\Logs\\excel-files\\";

    @PostMapping("/generate")
    public ResponseEntity<String> generateAndSaveExcel(@RequestBody ExcelRequest request) {
        // Use the context name directly as requested (e.g., "admin_view")
        String context = (request.getContextName() != null) ? request.getContextName() : "output";

        log.info(">>> API HIT: Received request for Context: '{}'", context);

        try {
            // 1. Generate Excel (Service now injects the hidden metadata signature)
            byte[] excelContent = excelService.generateGenericExcel(request);

            // 2. Filename is clean and readable
            String filename = context + ".xlsx";

            log.info("Saving file as: '{}' (Hidden signature injected inside file)", filename);

            // 3. Save file
            Path path = Paths.get(OUTPUT_FOLDER + filename);

            if (!Files.exists(path.getParent())) {
                Files.createDirectories(path.getParent());
            }

            Files.write(path, excelContent);
            log.info(">>> SUCCESS: File saved.");

            return ResponseEntity.ok("SUCCESS: File created at " + path.toAbsolutePath());

        } catch (IOException e) {
            log.error(">>> ERROR: IO Exception.", e);
            return ResponseEntity.internalServerError().body("ERROR: " + e.getMessage());
        } catch (Exception e) {
            log.error(">>> ERROR: Unexpected error.", e);
            return ResponseEntity.internalServerError().body("Unexpected Error: " + e.getMessage());
        }
    }

    @PostMapping("/verify")
    public ResponseEntity<String> verifyExcelFile(@RequestParam("file") MultipartFile file) {
        if (file.isEmpty()) {
            return ResponseEntity.badRequest().body("Please upload a file.");
        }

        try (XSSFWorkbook workbook = new XSSFWorkbook(file.getInputStream())) {

            // 1. Get the properties
            String signature = null;
            try {
                // POI 5.x returns a CTProperty object, not a String directly
                CTProperty property = workbook.getProperties()
                        .getCustomProperties()
                        .getProperty("X-Platform-Auth");

                if (property != null) {
                    // Extract the string value (Lpwstr = Long Pointer to Wide String)
                    signature = property.getLpwstr();
                }
            } catch (Exception e) {
                // Property might not exist or other error
                log.warn("Could not read custom property", e);
            }

            // 2. Validate
            String SECRET_KEY = "PLT_SECURE_SIG_V1"; // Must match Service key

            if (SECRET_KEY.equals(signature)) {
                return ResponseEntity.ok("VALID: This file was generated by our Generic Platform.");
            } else {
                return ResponseEntity.status(401).body("INVALID: Signature missing or incorrect. This might be a standard Excel file.");
            }

        } catch (IOException e) {
            return ResponseEntity.internalServerError().body("Error reading file: " + e.getMessage());
        }
    }
}