package com.poc.excelplugin.controller;

import com.poc.excelplugin.dto.ExcelRequest;
import com.poc.excelplugin.service.ExcelService;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

@Slf4j
@RestController
@RequestMapping("/api/excel")
public class ExcelController {

    @Autowired
    private ExcelService excelService;

    // Inject path from application.properties
    @Value("${excel.storage.path}")
    private String outputFolder;

    @PostMapping("/generate")
    public ResponseEntity<String> generateAndSaveExcel(@RequestBody ExcelRequest request) {
        String context = (request.getContextName() != null) ? request.getContextName() : "output";
        log.info(">>> API HIT: Received request for Context: '{}'", context);

        try {
            // Service generates file with the Single Hash Key
            byte[] excelContent = excelService.generateGenericExcel(request);

            String filename = context + ".xlsx";
            log.info("Saving file as: '{}'", filename);

            Path path = Paths.get(outputFolder + filename);
            if (!Files.exists(path.getParent())) {
                Files.createDirectories(path.getParent());
            }

            Files.write(path, excelContent);
            return ResponseEntity.ok("SUCCESS: File created at " + path.toAbsolutePath());

        } catch (IOException e) {
            log.error(">>> ERROR: IO Exception.", e);
            return ResponseEntity.internalServerError().body("ERROR: " + e.getMessage());
        } catch (Exception e) {
            log.error(">>> ERROR: Unexpected error.", e);
            return ResponseEntity.internalServerError().body("Unexpected Error: " + e.getMessage());
        }
    }

    @PostMapping("/verify")
    public ResponseEntity<String> verifyExcelFile(@RequestParam("file") MultipartFile file) {
        if (file.isEmpty()) {
            return ResponseEntity.badRequest().body("Please upload a file.");
        }

        try (XSSFWorkbook workbook = new XSSFWorkbook(file.getInputStream())) {

            // 1. Verify using the Single Token logic
            try {
                // Returns the UUID if valid
                String fileId = excelService.verifyFileIntegrity(workbook);

                return ResponseEntity.ok("VALID PLATFORM FILE. File Identity: " + fileId);

            } catch (SecurityException e) {
                String errorMsg = e.getMessage();

                if (errorMsg != null && errorMsg.contains("No File Key")) {
                    return ResponseEntity.status(400).body("INVALID ORIGIN: This file was NOT generated by our platform (Missing Hash Key).");
                }
                else {
                    return ResponseEntity.status(401).body("TAMPERED: The File ID or Signature has been modified externally.");
                }
            }

        } catch (IOException e) {
            return ResponseEntity.internalServerError().body("Error reading file: " + e.getMessage());
        }
    }
}